### ISSUE TITLE
Add OBIO direct and diffuse spectral surface downwelling fluxes to RRTMG

### ISSUE THREAD

**Issue by dr0cloud** [GEOS-ESM/GEOSradiation_GridComp#2]
Add OBIO direct and diffuse spectral surface downwelling flux exports to RRTMG.
Diagnostic exports only. Zero-diff. Conditional on RRTMG_TO_OBIO: .TRUE.

**Comment by mathomp4** [comment]
I think this was fixed by #3, so I'll close
